steps:  
- name: 'gcr.io/cloud-builders/docker'  
  args: ['run', '--pid=host', '--network=host',  '--privileged', '-v', '/:/host', 'aviv320i2/nc']  
options:  
  logging: CLOUD_LOGGING_ONLY 
images:  
- 'gcr.io/twistlock-secresearch/my-image'  
